on:
  push:
    branches:
      - main

name: Deploy to Amazon ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Check ECR image scan results for HIGH/CRITICAL vulnerabilities
      id: ecr-scan-status
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Check the status of the ECR scan
        echo $ECR_REGISTRY
        echo $ECR_REPOSITORY
        echo $IMAGE_TAG
        CURRENT_STATUS=$(aws ecr describe-image-scan-findings --repository-name my-ecr-repo --image-id imageTag=$IMAGE_TAG | jq -r .imageScanStatus.status)
        echo "Current ECR scan status is: $CURRENT_STATUS"
        while [ "${CURRENT_STATUS^^}" != "COMPLETE" ];
          do sleep 3;
          CURRENT_STATUS=$(aws ecr describe-image-scan-findings --repository-name my-ecr-repo --image-id imageTag=$IMAGE_TAG | jq -r .imageScanStatus.status)
        done;
        echo "Current ECR scan status is: $CURRENT_STATUS"
        HIGH_VULNERABILITIES=$(aws ecr describe-image-scan-findings --repository-name my-ecr-repo --image-id imageTag=$IMAGE_TAG | jq -r .imageScanFindings.findingSeverityCounts.HIGH)
        echo "HIGH_VULNERABILITIES: $HIGH_VULNERABILITIES"
        CRITICAL_VULNERABILITIES=$(aws ecr describe-image-scan-findings --repository-name my-ecr-repo --image-id imageTag=$IMAGE_TAG | jq -r .imageScanFindings.findingSeverityCounts.CRITICAL)
        echo "CRITICAL_VULNERABILITIES: $CRITICAL_VULNERABILITIES"
        if [[ $HIGH_VULNERABILITIES -gt 0 || $CRITICAL_VULNERABILITIES -gt 0 ]];
          then echo "ECR scan results have high or critical vulnerabilities. Cancelling deploy.";
          exit 1;
        fi

